# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ec2044f0a8daf0c7684aa47f6dcadec1c5a0dd7fb40a375f60a69e898661bada1ff56c47eae5d1ec0de975ca5c6a7c99c632cfce5487189ddfa772744a38b7a

test:
  secret_key_base: 38a0ec91ac75dc968c3917211c3f41d06dcce127bdf61f00c0a9ed572d16d28ffeecd935b2b1d9802165c693314f16e938efe7bfe82c372e0aaaed17920d5fb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
